package constant

const (
	HomePage             string = "html\\frontwebPage.html"
	WorldTemplate        string = "html\\worldwebPage.html"
	StatesTemplate       string = "html\\countrystateswebPage.html"
	VaccineTemplate      string = "html\\vaccinationwebPage.html"
	IndiaTemplate        string = "html\\indiawebPage.html"
	ALLKey               string = "All"
	ConfirmedKey         string = "confirmed"
	RecoveredKey         string = "recovered"
	DeathsKey            string = "deaths"
	CountryKey           string = "country"
	CapitalCityKey       string = "capital_city"
	UpdatedKey           string = "updated"
	People_VaccinatedKey string = "people_vaccinated"
	PopulationKey        string = "population"
	WorldKey             string = "World"
	GlobalKey            string = "Global"
	ContinentalNA        string = "North America"
	ContinentalUS        string = "United States"
	ContinentalE         string = "Europe"
	ContinentalAS        string = "Asia"
	ContinentalEU        string = "European Union"
	ContinentalSA        string = "South America"
	ContinentalAF        string = "Africa"
)
